
def main():
    socket_funcs_file = open('dom_builder/socket_parse.js', 'r')
    socket_funs = socket_funcs_file.read()

    final = f'''
    // Code generated by gojs/dom-builder. DO NOT EDIT.
    // source dom_builder.go

    package gojs

    import "fmt"

    type DOMBuilder struct [|
        SocketURI string
        HTMLHeadTags string
    |]

    func (b *DOMBuilder) Build() string [|
        return fmt.Sprintf(`
            <html>			
                <head>
                    %s

                    <script>
                        const socket = new WebSocket("%s")

                        {socket_funs}

                        initializeSocket(socket)
                    </script>
                </head>
                <body>
                </body>
            </html>
        `, b.HTMLHeadTags, b.SocketURI)
    |]
    '''

    with open('dom_builder.go', 'w') as f:
        f.write(final.replace('[|', '{').replace('|]', '}'))


if __name__ == "__main__": 
    try:
        main()
        print("dom builder ran successfully.")
    except:
        print("error occurred when running dom builder.")
